### PR TITLE
[New feature] Nmap scan and import from db

### PR DESCRIPTION
**Pull request by cyrinux**
* Nmap top 1000 TCP and UDP scan then import done with `nmap_scan [-f, -o params,...] ip` 
* `nmap` renamed to `nmap_import`

### CODE REVIEW

**Comment by cyrinux** [comment]
I got some idea to improve this but maybe in a next iteration. Like a interactive mode for choose some "scan" preset? What do you think about? Maybe start it in a thread? Feel free to try/merge it. :)

**Comment by cyrinux** [comment]
I'm - trying to - implementing threading with progressbar finally. I progress.

**Comment by koutto** [comment]
Cool; will check that asap !

**Comment by cyrinux** [comment]
This is totally improvable, but i'm a little stuck for example, i don't understand why when i run my scan one time i see my progress bar, but i can't run it a second time then without exit the program then restart it.

image

**Comment by cyrinux** [comment]
Also, I search a way to get a progress for the full scan if we got TCP and UDP for example, from what i understand the progress counter back to 0 on each protocol.
And better way to handle this can be with the NmapProcess `evant_callback` I imagine.

**Comment by cyrinux** [comment]
It's not so bad now

**Comment by cyrinux** [comment]
I don't find how to not stack/clean previous aborted scan for example. But this do the work.

Peek 2019-07-26 12-11

**Review by ghost — APPROVED** [review]

**Comment by cyrinux** [comment]
Hi @koutto, is this project abandoned ?

**Pull request closed without merging**
