### PR TITLE
Add WAF matchstrings support, Cloudmare for cloudflare realip detection and DOMAIN tag

### PR DESCRIPTION
**Pull request by cyrinux**
I take Cloudflare context from wafw00f and wappanalyzer for the moment.

I then check the root domain on cloudmare, i fetch the root domain with a tricky way, if you can provider a placeholder like [DOMAIN] it would be nice.

### CODE REVIEW

**Comment by cyrinux** [comment]
I try to place `[DOMAIN]` in the code. @koutto in which part of the model do you see that?

**Comment by koutto** [comment]
@cyrinux Hey, sorry i don't have time right now to check everything. I will tomorrow.

Supporting waf is a good idea. Maybe you could add the whole list of waf detected by wafw00f as the list of supported waf inside http.conf, and not only CloudFlare.

To add new tags supported in commands, it is inside lib/core/Command.py
But maybe, the tag [HOSTNAME] is enough for your need ? I let you check, and will give a look tomorrow !

**Comment by cyrinux** [comment]
Thanks you @koutto, I will try to do this.
No HOSTNAME is not sufficiant, in my try, Cloudmare take the DOMAIN (root domain), maybe another tools do the same job and accept the HOSTNAME or URL directly but i have not found.
Take you time to review / correct me ;)

**Comment by cyrinux** [comment]
* All waf from wafw00f 1.0.0 were added, so i upgraded from 0.9.5.
* `[DOMAIN]` is working for me.

* Need to check if waf detection (regex) from wafw00f works well btw

**Comment by cyrinux** [comment]
FYI, I got a problem yet, the webanalyzer context matching for cloudflare works but not with wafw00b. I search the problem.

**Comment by cyrinux** [comment]
Regex fixed

**Comment by koutto** [comment]
Thanks for this good job @cyrinux 

I just made minor adjustements before merging: https://github.com/koutto/jok3r/commit/e05440df735edbd3d399c9d73ec910ed8972cc62 

Thanks !

**Pull request merged**
