### PR TITLE
[improvement] Add shodan ips import

### PR DESCRIPTION
**Pull request by cyrinux**
Need to set api key in bottom of Config.py

### CODE REVIEW

**Comment by koutto** [comment]
Cool that you work on that feature. A few comments regarding this:

1. Lack of checks on data, i got this error from a random ip I took on shodan:

> jok3rdb[test_shodan]> shodan 117.6.64.121
> 
> [*] Importing Shodan results from 117.6.64.121
> [*] Each service will be re-checked to detect HTTP services. Use --no-http-recheck if you want to disable it (faster import)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 1742, in onecmd_plus_hooks
>     stop = self.onecmd(statement)
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 2050, in onecmd
>     stop = func(statement)
>   File "/usr/local/lib/python3.7/dist-packages/cmd2/cmd2.py", line 270, in cmd_wrapper
>     return func(cmd2_instance, args)
>   File "/root/jok3r/lib/controller/DbController.py", line 1271, in do_shodan
>     grab_html_title=not args.no_html_title)
>   File "/root/jok3r/lib/core/ShodanResultsParser.py", line 60, in parse
>     hostname = host_report.get('hostnames', '')[0]
> IndexError: list index out of range
> EXCEPTION of type 'IndexError' occurred with message: 'list index out of range'


2. Name of services used on Shodan can vary. For example on https://www.shodan.io/host/117.6.64.121 I can see that there are HTTP services that are tagged "http-simple-new" or "https-simple-new" (and maybe other unusual names for designing common services). In this example, they should of course be categorized as HTTP in Jok3r, and so the matching table between services in Config.py should be adapted accordingly. 

3. I think the API key should be stored somewhere else to avoid committing the API key on the repo. It should be put in a dedicated file which should be gitignored

**Comment by cyrinux** [comment]
* I will add some check and do more tests and try to add maximum shodan to jok3r i find :)
* What do you think about setting the key in the sqlite database? You prefer a key file stored in home for for example over so a 'set shodan_api_key key' ?
I can start by an external file as you said, will be simple for a first version maybe but tell me.

**Comment by cyrinux** [comment]
I made few fix and move api key to a file.

**Comment by cyrinux** [comment]
I don't have visio for edit the architecture document but here the shodan logo https://upload.wikimedia.org/wikipedia/commons/f/ff/Shodan_logo.png
Do you really use visio or an alternative?

**Comment by cyrinux** [comment]
Or what do you think about storing api key in `settings/shodan.conf`?

**Comment by koutto** [comment]
I will give a look tomorrow. Storing the key in settings/shodan.conf is good idea.
For the architecture diagram, dont worry, i will update it later on Visio.

**Comment by cyrinux** [comment]
I think we can use get_specific_option_type from ServiceConfig to get the API key. Will try this.

**Comment by cyrinux** [comment]
I finish for my part, idea i got in head for this first iteration, I let you review.
About api key storage, I think its better you make it ^^

**Comment by koutto** [comment]
I don't know if it was a concern in your code, but don't waste time on os_vendor and os_family when adding target. I am currently working on refactoring and modifying minor stuff inside Target and AttackScope/AttackController, I have added a OSUtils class to get vendor/os_family from an OS String. After merging your PR, I will add the appropriate call to those methods ;)

**Comment by cyrinux** [comment]
@koutto nice ! I spot these branch yes :)
* I was yet lost about this point thx, from shodan I can only get "os" which is for example `Windows Server 2016 Essentials` or `null` for a Synology disk station...which run linux..., from example here https://www.shodan.io/host/107.149.125.208/raw or https://www.shodan.io/host/173.66.204.246/raw

**Comment by cyrinux** [comment]
I got visio so I finally edit the architecture schemas.

**Comment by koutto** [comment]
I implement API keys support which I actually also need for Vulners checks (and maybe for other checks in the future). And then, I resolve conflicts and merge this branch ;)

**Comment by cyrinux** [comment]
Ok cool, good news :)

**Comment by cyrinux** [comment]
I just rebased on master. I let you make the merge of this, i'm afraid to make overcomplicated 💩 . Maybe this can do the job?
image

**Comment by koutto** [comment]
Hey,
I've merged this PR. I've made several modifications:
- Change the banner retrieval to get only product name + version if available and not the full content of 'data'.
- Handle correctly HTTPS to build correct URL
- Add call to Target.smart_check() in order to check availability, detect web technos for HTTP services (service provided by Shodan does not return versions of technos, so it is better to run it here) and update context stored in db with SmartStart class.

Thanks for the work.

**Comment by cyrinux** [comment]
Thx @koutto, check your mail :P

**Pull request closed without merging**
